### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#438] opened 2017-10-04 11:08 UTC
Bot version: 5.7.2

Node.js version: v8.6.0

Npm version: 5.3.0

Does node_modules folder and package-lock.json remove and npm install solved issue?: no

Issue description: crash bot

Expected result: fix issue

[exceptions-2017-10-03T21_21_50.log](https://github.com/sogehige/sogeBot/files/1355539/exceptions-2017-10-03T21_21_50.log)

**Comment by sogehige** [comment] 2017-10-04 15:01
This has something to do with logging on events, although, I cannot reproduce this issue.
Do you know when exactly is bot crashing on what event?

**Comment by sogehige** [comment] 2017-10-04 15:42
I'll close this issue, I cannot reproduce logging error even with db, not sure what went wrong, will keep an eye on that

**Comment by sogehige** [comment] 2017-10-04 15:44
Nevermind, reproduced

**Closed** 2017-10-04 16:02 UTC
Labels: bug, done
