### ISSUE TITLE
Eventlist not working properly

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#1333] opened 2018-09-20 13:26 UTC
### Expected behavior
Follow events aren't appearing in eventlist and aren't in the db either.
### Actual behavior
Both is authenticated and channel is authenticated. I can see the stats change from the new follower but nothing appears in eventlist. The notifications are green in the panel. I've tried turning them red as well but still nothing in eventlist. Not sure what you would need to figure out whats going on.

### Steps to reproduce
On my bot it's working on version 8.0.2 (Upgraded from 7.5.1)

On new bot 8.0.2 (Fresh) eventlist isn't working properly.

**Comment by Banonevar** [comment] 2018-09-20 20:05
I guess you need provide eventlist collection

**Comment by ic3dr460n** [comment] 2018-09-21 12:44
I mentioned that but there isn't anything in it. So not sure how much help it would be.

**Comment by sogehige** [comment] 2018-09-23 23:03
Isn't this same issue as #1312?

**Comment by sogehige** [comment] 2018-11-15 09:57
Closing as cannot reproduce

**Closed by sogehige** 2018-11-15 09:57 UTC
Labels: cannot reproduce
