### ISSUE TITLE
Upgrade from 10.6.0 to 10.6.1 Causes Bot to Crash on Startup

### ISSUE THREAD

**Issue by MoonlightAshe** [sogehige/sogeBot#3272] opened 2020-02-18 08:49 UTC
### Expected behavior
Bot starts up without crashing.

### Actual behavior
Bot crashes upon updating if using SQLITE with database used with 10.6.0. It does not crash if there is no DB when it starts up.

### Steps to reproduce
Start up bot while using SQLITE with a database that was working with 10.6.0. 

### Additional informations

Upgraded from 10.6.0 to 10.6.1.
`2020-02-18T02:40:14.303 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
      at new DriverPackageNotInstalledError (/home/user/sogebot/src/error/DriverPackageNotInstalledError.ts:8:9)
      at SqliteDriver.loadDependencies (/home/user/sogebot/src/driver/sqlite/SqliteDriver.ts:128:19)
      at new SqliteDriver (/home/user/sogebot/src/driver/sqlite/SqliteDriver.ts:46:14)
      at DriverFactory.create (/home/user/sogebot/src/driver/DriverFactory.ts:41:24)
      at new Connection (/home/user/sogebot/src/connection/Connection.ts:126:43)
      at ConnectionManager.create (/home/user/sogebot/src/connection/ConnectionManager.ts:64:28)
      at Object.<anonymous> (/home/user/sogebot/src/index.ts:231:35)
      at step (/home/user/sogebot/node_modules/tslib/tslib.js:136:27)
      at Object.next (/home/user/sogebot/node_modules/tslib/tslib.js:117:57)
      at /home/user/sogebot/node_modules/tslib/tslib.js:110:75 {
    name: 'DriverPackageNotInstalledError',
    message: 'SQLite package has not been found installed. Try to install it: npm install sqlite3 --save'
  }
} reason: DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
2020-02-18T02:40:17.100 | CURRENCY: fetching rates
2020-02-18T02:40:17.349 | CURRENCY: fetched rates
2020-02-18T02:40:22.107 !!! ERROR !!! ConnectionNotFoundError: Connection "default" was not found.
    at new ConnectionNotFoundError (/home/user/sogebot/src/error/ConnectionNotFoundError.ts:8:9)
    at ConnectionManager.get (/home/user/sogebot/src/connection/ConnectionManager.ts:40:19)
    at Object.getRepository (/home/user/sogebot/src/index.ts:285:35)
    at Timeout._onTimeout (/home/user/sogebot/src/bot/socket.ts:54:9)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  name: 'ConnectionNotFoundError',
  message: 'Connection "default" was not found.'
}`

**Comment by sogehige** [comment] 2020-02-18 09:34
`npm install sqlite3 --save`

**Comment by MoonlightAshe** [comment] 2020-02-18 16:20
Causes spectacular errors after using that. Fixed by deleting everything in the Settings table within the database and redoing the Settings afterwards.

**Comment by sogehige** [comment] 2020-02-18 16:30
Settings issue is not a bug and don't belong to this issue. Closing as fixed

**Closed by sogehige** 2020-02-18 16:30 UTC
