### ISSUE TITLE
Doubled chat connection on 1 bot instance

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#3849] opened 2020-06-01 14:06 UTC
### Actual behavior
I have very weird bug.

One of my bot instance trying to connect on channel 2 times.

It happens on start. Interval before connections 30-40 seconds.
### Steps to reproduce
It's weird because i cannot reproduce it on other bot instanced.

Also i tried setup new DB for that bot, without data migraion. I just setuped bot and filled tokens, channel. And... anyways connection to chat is doubled.
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/78e1e1dea9a13426ee1629e805809e5ba64db18a, postgres 11.5

**Comment by sogehige** [comment] 2020-11-20 13:32
I cannot reproduce this issue. Closing

**Closed by sogehige** 2020-11-20 13:32 UTC
Labels: cannot reproduce
