### ISSUE TITLE
Streamlabs/tips not working correctly

### ISSUE THREAD

**Issue by ic3dr460n** [sogehige/sogeBot#897] opened 2018-04-07 21:46 UTC
When donating using streamlabs bot doesn't see the event nor does it update tips stats for user. I have to update user manually still.

Also is it possible to import all past donations into bot automatically??

**Comment by sogehige** [comment] 2018-04-07 22:10
Any errors?

Also is it possible to import all past donations into bot automatically?? < no

**Comment by sogehige** [comment] 2018-04-07 22:29
I could not reproduce, event is correctly saved in `user.tips` collection and in eventlist

**Comment by sogehige** [comment] 2018-04-07 22:30
although tips are not correctly saved in dashboard stats

**Comment by sogehige** [comment] 2018-04-08 00:03
Should be fixed in 7.0.4

**Closed** 2018-04-09 21:28 UTC
Labels: bug, done
