### ISSUE TITLE
Currency exchange error - EUR code was not found

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2229] opened 2019-05-29 12:57 UTC
### Actual behavior
When user who has tips in EUR currency, got this error
```Currency exchange error - EUR code was not found```
Main currency of a bot it's RUB
### Steps to reproduce
Currency fetched
```
2019-05-28T23:29:16.926 | CURRENCY: fetching rates
 2019-05-28T23:29:17.000 | CURRENCY: fetched rates
```
Also i added `console.log(this.rates)`, and it seems correct (cated) 
```
{
  EUR: '25.845',
  RUB: '0.358',
}
```
Some example from db:
```
{ "_id" : ObjectId("5cd4849d7574d2443f953a63"), "id" : "hidden", "amount" : "1.50", "message" : "", "currency" : "EUR", "timestamp" : 1541005190113 }
```
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/4c4128446568a3e8d67b3558974dd9b3604b4dc8

**Comment by sogehige** [comment] 2019-06-04 10:31
I cannot reproduce this issue, do you have more/better steps to reproduce?

Tests: https://github.com/sogehige/sogeBot/pull/2233

**Comment by Banonevar** [comment] 2019-06-04 11:06
Well, user just use !me command i guess

**Comment by Banonevar** [comment] 2019-06-04 11:06
I can send whole db if it will helps

**Comment by Banonevar** [comment] 2019-06-04 11:09
```
2019-06-04T11:29:25.683 <<< !me [hidden]
2019-06-04T11:29:25.844 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.844 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.844 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.844 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.844 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.844 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.845 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.846 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.846 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.850 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.850 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.850 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.850 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.850 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.851 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.852 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.852 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.852 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.852 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.852 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.852 |! Currency exchange error - EUR code was not found 
2019-06-04T11:29:25.908 >>> @hidden | 99.0h | 990 mp | 26 сообщений | 10486.93₽ [hidden]
```

**Comment by sogehige** [comment] 2019-06-05 12:40
I'll expand error message, which should list available currencies https://github.com/sogehige/sogeBot/pull/2239

**Comment by Banonevar** [comment] 2019-06-05 18:47
2019-06-05T20:46:49.596 !!! ERROR !!! TypeError: this.rates.join is not a function
at Currency.join [as exchange] (/root/bots/src/bot/currency.js:65:62)

**Comment by sogehige** [comment] 2019-06-05 18:49
Oh I see I am dumb will fix

Dne st 5. 6. 2019 20:47 uživatel Banonevar <notifications@github.com>
napsal:

**Comment by sogehige** [comment] 2019-06-10 17:08
Error should be fixed here https://github.com/sogehige/sogeBot/pull/2243

**Comment by sogehige** [comment] 2019-06-18 06:47
Why is this closed?

**Comment by Banonevar** [comment] 2019-06-18 06:56
I think i missclicked
I want new comment
```
2019-06-18T08:56:17.906 |! Currency exchange error - EUR code was not found
2019-06-18T08:56:17.906 |! Available currencies: CZK
```

**Comment by sogehige** [comment] 2019-06-18 06:58
So rates are no correctly loaded

**Comment by sogehige** [comment] 2019-06-18 06:58
do you have access to http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.txt ?

**Comment by Banonevar** [comment] 2019-06-18 06:59
Yes

**Comment by Banonevar** [comment] 2019-06-18 06:59
```
root@home:~# curl http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.txt
17.06.2019 #115
země|měna|množství|kód|kurz
Austrálie|dolar|1|AUD|15,629
Brazílie|real|1|BRL|5,839
Bulharsko|lev|1|BGN|13,068
Čína|žen-min-pi|1|CNY|3,286
Dánsko|koruna|1|DKK|3,423
EMU|euro|1|EUR|25,560
Filipíny|peso|100|PHP|43,541
Hongkong|dolar|1|HKD|2,906
Chorvatsko|kuna|1|HRK|3,452
Indie|rupie|100|INR|32,529
Indonesie|rupie|1000|IDR|1,587
Island|koruna|100|ISK|18,064
Izrael|nový šekel|1|ILS|6,305
Japonsko|jen|100|JPY|20,940
Jižní Afrika|rand|1|ZAR|1,535
Kanada|dolar|1|CAD|16,963
Korejská republika|won|100|KRW|1,917
Maďarsko|forint|100|HUF|7,931
Malajsie|ringgit|1|MYR|5,445
Mexiko|peso|1|MXN|1,187
MMF|ZPČ|1|XDR|31,474
Norsko|koruna|1|NOK|2,610
Nový Zéland|dolar|1|NZD|14,811
Polsko|zlotý|1|PLN|6,000
Rumunsko|leu|1|RON|5,406
Rusko|rubl|100|RUB|35,428
Singapur|dolar|1|SGD|16,597
Švédsko|koruna|1|SEK|2,400
Švýcarsko|frank|1|CHF|22,793
Thajsko|baht|100|THB|72,610
Turecko|lira|1|TRY|3,876
USA|dolar|1|USD|22,752
Velká Británie|libra|1|GBP|28,651
```

**Comment by sogehige** [comment] 2019-06-18 12:40
Strange...would you be able to update currency file for result data?

```javascript
      // currency.ts#70
      const result = await axios.get('http://www.cnb.cz/cs/financni_trhy/devizovy_trh/kurzy_devizoveho_trhu/denni_kurz.txt');
      console.log(result.data)
```

**Comment by sogehige** [comment] 2019-06-18 16:34
nevermind, I actually reproduced it

**Closed** 2019-06-18 17:10 UTC
