### ISSUE TITLE
Crash: attr.fnc is not a function

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#336] opened 2017-06-11 18:27 UTC
```

0|glinbot  | 2017-06-11T21:07:34.778 !!! ERROR !!! uncaughtException: attr.fnc is not a function
0|glinbot  | 2017-06-11T21:07:53.516 !!! ERROR !!! +------------------------------------------------------------------------------+
0|glinbot  | 2017-06-11T21:07:53.517 !!! ERROR !!! | BOT HAS UNEXPECTEDLY CRASHED                                                 |
0|glinbot  | 2017-06-11T21:07:53.517 !!! ERROR !!! | PLEASE CHECK https://github.com/sogehige/SogeBot/wiki/How-to-report-an-issue |
0|glinbot  | 2017-06-11T21:07:53.518 !!! ERROR !!! | AND ADD logs/exceptions.log file to your report                              |
0|glinbot  | 2017-06-11T21:07:53.518 !!! ERROR !!! +------------------------------------------------------------------------------+
0|glinbot  | 2017-06-11T21:07:53.520 !!! ERROR !!! uncaughtException: attr.fnc is not a function
0|glinbot  | 2017-06-11T21:07:58.144 !!! ERROR !!! Possibly Unhandled Rejection
0|glinbot  | 2017-06-11T21:07:58.151 !!! ERROR !!! Promise { <rejected> 'No response from Twitch.' }
0|glinbot  | 2017-06-11T21:08:12.256 !!! ERROR !!! +------------------------------------------------------------------------------+
0|glinbot  | 2017-06-11T21:08:12.257 !!! ERROR !!! | BOT HAS UNEXPECTEDLY CRASHED                                                 |
0|glinbot  | 2017-06-11T21:08:12.258 !!! ERROR !!! | PLEASE CHECK https://github.com/sogehige/SogeBot/wiki/How-to-report-an-issue |
0|glinbot  | 2017-06-11T21:08:12.258 !!! ERROR !!! | AND ADD logs/exceptions.log file to your report                              |
0|glinbot  | 2017-06-11T21:08:12.258 !!! ERROR !!! +------------------------------------------------------------------------------+
0|glinbot  | 2017-06-11T21:08:12.259 !!! ERROR !!! uncaughtException: attr.fnc is not a function

```

https://satont.xyz/s/log.log

**Comment by sogehige** [comment] 2017-06-11 19:17
I will need events from db to check what is happening

**Comment by sogehige** [comment] 2017-06-11 19:17
And please, can you do more useful titles?

**Comment by Satont** [comment] 2017-06-11 19:26
Sry for title
Yep, there is db:
https://satont.xyz/s/db.db

**Comment by sogehige** [comment] 2017-06-11 19:28
Does this bot have https://github.com/sogehige/sogeBot/commit/134783755389d5b868d175c2b027a893f3e97768 fix?

**Comment by sogehige** [comment] 2017-06-11 19:33
Also it is duplicate of https://github.com/sogehige/sogeBot/issues/332

**Comment by Satont** [comment] 2017-06-11 23:12
Problem was with it?

**Comment by Satont** [comment] 2017-06-12 07:21
Yes, right, it fix my problem.

**Closed** 2017-06-12 07:21 UTC
Labels: duplicate, invalid
