### ISSUE TITLE
Users got overpointed

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1302] opened 2018-09-09 05:17 UTC
### Actual behavior
For some reason users start get thouthands points, but in settings it setted lower then they got
I sent you some db's in discord PM
### Additional informations

Mongodb, latest master (https://github.com/sogehige/sogeBot/commit/d13ec03d41c964f2eccccf80881221d0c6feee39)

**Comment by sogehige** [comment] 2018-09-23 23:06
What you sent is definitely not latest master as you said in discord

**Comment by Banonevar** [comment] 2018-09-23 23:13
It was for that moment, but its still exists, so problem are same on master

**Comment by sogehige** [comment] 2018-09-23 23:40
Cannot reproduce, tried online/offline stream, messages, and points intervals

**Comment by Banonevar** [comment] 2018-09-24 00:36
What i can do then? Maybe i can remove some settings, collections.. it's anoying problem for me

**Comment by Banonevar** [comment] 2018-09-24 00:41
[new.zip](https://github.com/sogehige/sogeBot/files/2409370/new.zip)
Can you check that? it's latest master

**Comment by sogehige** [comment] 2018-09-24 00:42
Maybe send users, users.online, users.points when under load

**Comment by Banonevar** [comment] 2018-09-24 00:42
[users.online.zip](https://github.com/sogehige/sogeBot/files/2409377/users.online.zip)
it's users online then.

**Comment by sogehige** [comment] 2018-09-24 00:50
Still cannot reproduce, please try latest master, I did some changes to interval, although it was not direcly fixing this issue

**Comment by sogehige** [comment] 2018-10-12 08:41
Fixed by cfb718a304ff6cf2621fe4f87ef1192c3f59af6a

**Closed by sogehige** 2018-10-12 08:41 UTC
Labels: bug
