### ISSUE TITLE
Add song playlist custom start and stop times

### ISSUE THREAD

**Issue by scott-42** [sogehige/sogeBot#620] opened 2017-12-22 17:17 UTC
This is a feature request to add in custom start and stop times for playlist songs.

In the Manage:Songs page the start and stop times are in edit boxes that don't do anything currently. I would like them to be editable and saved to the playlist DB to change the start time and stop time for the playlist items.

For example: This song is length 04:11
    Song: WSUFzC6_fp8
    Start: 00:00:03
    Stop: 00:03:14

**Comment by sogehige** [comment] 2017-12-22 17:19
Hmm. are you sure those text boxes doesnt do anything? If not its a bug, it should work as you described

**Comment by scott-42** [comment] 2017-12-22 17:39
Looking at the DB entry I don't see how they could have worked. I only see a length_seconds entry which looks like a cached version of the song length used for display in the playlist.

{"videoID":"WSUFzC6_fp8","title":"[Official Video] Carol of the Bells - Pentatonix","loudness":"-17.1690006256","length_seconds":"251","lastPlayedAt":1513929206807,"seed":1,"_id":"0BlSA6mvO4S8n5sx"}

**Comment by sogehige** [comment] 2017-12-22 17:42
If you change those textboxes, it should be changed to
{"videoID":"u9Dg-g7t2l4","title":"Disturbed  - The Sound Of Silence [Official
 Music Video]","loudness":"-18.8190002441","length_seconds":"259","lastPlayed
At":1464278126991,"_id":"ze68NJVhUbs2c1hO","seed":1,**"startTime":0,"endTime":2
59**}

If not, then change is not correctly propagated

**Comment by scott-42** [comment] 2017-12-22 18:24
The focus on the time editing box is getting lost after a second or so and setTrim is not getting called at all so I'm guessing that there is some problem with the editing and getting focusout. Browser info below since that might be relevant. I tested on two different browsers.

Browser: Firefox 57.0.1 (64-bit)
Browser: Chrome 63.0.3239.84 (Official Build) (64-bit)
OS: Ubuntu 16.04.03

**Comment by sogehige** [comment] 2017-12-22 18:54
Yes, problem is that playlist is loaded in interval which rewrites full table...

**Comment by sogehige** [comment] 2018-01-04 12:44
Actually issue was checking height offset, which made page to force rewrite again, because it took a lot of time. Removed this unnecessary code and updated page layout so it can be used without it - this issue should be fixed

**Comment by sogehige** [comment] 2018-01-04 12:52
Nope, still can reproduce...

**Comment by sogehige** [comment] 2018-01-04 14:53
Did some performance UI fixes and found cause of this issue, fixed

**Closed by sogehige** 2018-01-04 14:53 UTC
Labels: bug
