### ISSUE TITLE
Text alert not working

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#2986] opened 2019-11-17 20:48 UTC
### Actual behavior
!alert type=text text='Lorem Ipsum Dolor Sit Amet' will give you exactly nothing
### Steps to reproduce
1) add (or open) alerts overlay
2) type in chat !alert type=text text='Lorem Ipsum Dolor Sit Amet'
### Additional informations

master https://github.com/sogehige/sogeBot/commit/53a888f4ab3094925f5a8b1d2bea325885fadd3e

**Comment by sogehige** [comment] 2019-11-17 22:17
`!alert type=text text='Lorem Ipsum Dolor Sit Amet'` is working for me

**Comment by sogehige** [comment] 2020-01-26 13:43
Closing as I cannot reproduce and there is no follow up by reporter

**Closed by sogehige** 2020-01-26 13:43 UTC
Labels: cannot reproduce
