### ISSUE TITLE
Double message from timer

### ISSUE THREAD

**Issue by Satont** [sogehige/sogeBot#491] opened 2017-10-29 22:07 UTC
### Expected behavior
fix
### Actual behavior
Message for doubled
![img](https://satont.ru/s/1d96.png)
In this timer only 2 messages
Settings for this timer:
![img2](https://satont.ru/s/2V88.png)
Bot on my channel same thing (on screen other channel)
Its a bug
### Steps to reproduce
Idk, maybe create timer?
### Additional informations
Bot version: latest master
Node.js version: 8.6.0
Npm version:

**Comment by Satont** [comment] 2017-10-30 00:12
Sometimes triple messages, or 4 messages

**Comment by sogehige** [comment] 2017-10-30 01:28
Logs

Dne 30. 10. 2017 1:12 dop. napsal uživatel "Satont" <
notifications@github.com>:

Sometimes triple messages, or 4 messages

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sogehige/sogeBot/issues/491#issuecomment-340314848>,
or mute
the thread

**Comment by Satont** [comment] 2017-10-30 01:30
2017-10-30T01:04:10.446 on #1194
[sogebot-2017-10-29T23_03_57.log](https://github.com/sogehige/sogeBot/files/1425704/sogebot-2017-10-29T23_03_57.log)

**Comment by Satont** [comment] 2017-10-30 01:33
Maybe you need db dump or something more?

**Comment by sogehige** [comment] 2017-10-30 09:53
Yes please would need timersResponses and timers tables

**Comment by Satont** [comment] 2017-10-30 15:27
Timers:
```
{
    "_id" : ObjectId("59f52451acdace4c6a2d44e7"),
    "name" : "10",
    "messages" : 10,
    "seconds" : 600,
    "enabled" : true,
    "trigger" : {
        "messages" : 73,
        "timestamp" : 1509356812069.0
    }
}
```
timerResponses:
```
{
    "_id" : ObjectId("59f52469ff7d32491da7d92f"),
    "response" : "(!dj)",
    "timestamp" : 1509356812069.0,
    "enabled" : true,
    "timerId" : "59f52451acdace4c6a2d44e7"
}
{
    "_id" : ObjectId("59f5246fff7d32491da7d930"),
    "response" : "(!vk)",
    "timestamp" : 1509356810663.0,
    "enabled" : true,
    "timerId" : "59f52451acdace4c6a2d44e7"
}
```

**Comment by Satont** [comment] 2017-10-30 23:16
But as i said it happens with other bots too
![img3](https://satont.ru/s/4H36.png)

**Comment by sogehige** [comment] 2017-10-30 23:17
Are all of those responses commands?

**Comment by Satont** [comment] 2017-10-30 23:17
on latest screen - not
not command, its text

**Comment by sogehige** [comment] 2017-10-30 23:17
Ok, still trying to reproduce that

**Comment by sogehige** [comment] 2017-10-30 23:19
Problem is
```
2017-10-30T02:04:17.779 >>> Группа: vk.com/bogsh , Поддержать стримера: http://www.donationalerts.ru/r/bogsh , https://skindonate.com/ru/d/bogsh донат вещами дота... [satontx]
2017-10-30T02:04:17.788 >>> Группа: vk.com/bogsh , Поддержать стримера: http://www.donationalerts.ru/r/bogsh , https://skindonate.com/ru/d/bogsh донат вещами дота... [satontx]
```

Its 100ms, this shouldn't happen, timers are checked each second and only one response should be sent

**Comment by Satont** [comment] 2017-10-30 23:21
2017-10-31T02:12:13.593 >>> Вы можете заказать трек на стрим. Стоимость 10 рублей. http://www.donationalerts.ru/c/satontx [satontx]
2017-10-31T02:12:14.593 >>> Вы можете заказать трек на стрим. Стоимость 10 рублей. http://www.donationalerts.ru/c/satontx [satontx]


Strings from sceen

**Comment by sogehige** [comment] 2017-10-30 23:22
Hmm ok, so its interval thing and response is not properly updated, let me do quick fix if it will sort your issue

**Comment by sogehige** [comment] 2017-10-30 23:32
Please try latest master or https://github.com/sogehige/sogeBot/commit/b24c7f18f3694b5625f062a7a6ba8a45389d2663

**Comment by sogehige** [comment] 2017-10-31 21:14
Should be fixed now

**Closed by sogehige** 2017-10-31 21:14 UTC
Labels: bug, master only
