### ISSUE TITLE
Custom variable params with backslash are encoded

### ISSUE THREAD

**Issue by chiefstank** [sogehige/sogeBot#2599] opened 2019-09-22 15:42 UTC
### Expected behavior
Custom command that uses custom variable response. Parameter with backslash are encoded with unicode chars. If I escape the backslash in chat it works fine. This escaping was not required in 9.6.0. 

### Additional informations
2019-09-22T08:33:15.676 DEBUG: undefined ======= COPY DEBUG MESSAGE FROM HERE =======
2019-09-22T08:33:15.677 DEBUG: undefined GENERAL      | OS: npm/6.9.0 node/v12.3.1 win32 x64
2019-09-22T08:33:15.716 DEBUG: undefined              | Bot version: 9.7.2
2019-09-22T08:33:15.718 DEBUG: undefined              | DB: nedb
2019-09-22T08:33:15.719 DEBUG: undefined              | Threads: 1
2019-09-22T08:33:15.720 DEBUG: undefined              | HEAP: 56.16 MB
2019-09-22T08:33:15.720 DEBUG: undefined              | Uptime: 51612.202849769 seconds
2019-09-22T08:33:15.721 DEBUG: undefined              | Language: en
2019-09-22T08:33:15.722 DEBUG: undefined              | Mute: false
2019-09-22T08:33:15.722 DEBUG: undefined SYSTEMS      |
2019-09-22T08:33:15.723 DEBUG: undefined GAMES        |
2019-09-22T08:33:15.724 DEBUG: undefined INTEGRATIONS |
2019-09-22T08:33:15.725 DEBUG: undefined WIDGETS      | chat, eventlist
2019-09-22T08:33:15.726 DEBUG: undefined OAUTH        | BOT true | BROADCASTER true
2019-09-22T08:33:15.727 DEBUG: undefined ======= END OF DEBUG MESSAGE =======

**Comment by sogehige** [comment] 2019-09-23 15:05
Can I have more info? I am not sure that any code changed for custom variables between 9.6.0 and 9.7.0 and I cannot reproduce

**Comment by chiefstank** [comment] 2019-09-23 15:45
So while using 9.6.0 in my custom variable script I manually set the param for testing using the 'Test current script' which included backslashes which worked fine. In 9.7.2 I must escape each backslash when it's set within the script when I didn't have to in 9.6.0. 

Based on that I assume that IF the command actually triggered the custom variable script, the same thing would occur.

**Comment by sogehige** [comment] 2019-09-23 16:07
ok so return of custom variable by eval (script) is escaped?

**Comment by chiefstank** [comment] 2019-09-23 16:19
A test of the custom variable was done as follows.

**SCRIPT**
param = "GOM-Afreeca\2010\100828-101002 TG Sambo Intel StarCraft II Open Season 1\Ro32\2010-GSL-Season-1-Ro32-Match-1-Set-1_-_IdrA_vs_Nettie.mp4"
return param

**VALUE**
GOM-Afreeca0@828-101002 TG Sambo Intel StarCraft II Open Season 1Ro320-GSL-Season-1-Ro32-Match-1-Set-1_-_IdrA_vs_Nettie.mp4

If I escape each backslash when setting the param the return value is as expected. Again, this same test was done in 9.6.0 and it wasn't encoded like this while testing. 

ALSO, when my custom command called this custom variable (#2598) in 9.6.0, this escaping of the backslashes was NOT required. Below is how the command was working.

!request GOM-Afreeca\2010\100828-101002 TG Sambo Intel StarCraft II Open Season 1\Ro32\2010-GSL-Season-1-Ro32-Match-1-Set-1_-_IdrA_vs_Nettie.mp4

The return value would be the param exactly as it was sent using the command.

**Comment by sogehige** [comment] 2019-09-23 18:23
Actually not sure how it worked before, but this is standard behavior in javascript, you need to escape '\' in strings

**Comment by chiefstank** [comment] 2019-09-23 18:30
But when it wasn't escaped and triggered by the custom command it worked...

**Comment by sogehige** [comment] 2019-09-23 18:38
Would be nice to have proper step by steps of how did you use it

**Comment by chiefstank** [comment] 2019-09-23 18:44
Ok.

Chat command requires two parameters. First parameter is either 'set' or 'series' and the second parameter is a file path given outside of sogebot. NEITHER of these parameters are validated by sogebot. Instead, an object is created with the two parameters, encoded to base64 and send to a local server where it is validated and a response is given. 

Ex.
!requestvod series GOM-Afreeca\2010\100828-101002 TG Sambo Intel StarCraft II Open Season 1\Finals\2010-GSL-Season-1-Final-Set-1_-_HopeTorture_vs_Fruitdealer.mp4

Under 9.6.0 this worked without issue.

On 9.7.2, sogebot sees the 2nd parameter as:

GOM-Afreeca�0@828-101002 TG Sambo Intel StarCraft II Open Season 1Ro32�0-GSL-Season-1-Ro32-Match-1-Set-1_-_IdrA_vs_Nettie.mp4

instead of 

GOM-Afreeca\2010\100828-101002 TG Sambo Intel StarCraft II Open Season 1\Finals\2010-GSL-Season-1-Final-Set-1_-_HopeTorture_vs_Fruitdealer.mp4

For testing purposes the script in custom variables has been stripped down to only return the parameters sent by the command to check that it's correct.

**Comment by sogehige** [comment] 2019-09-23 22:01
closing as backslash should be escaped in JS

**Closed by sogehige** 2019-09-23 22:01 UTC
Labels: not a bug
