### ISSUE TITLE
Some parts are displayed in Russian, instead of English

### ISSUE THREAD

**Issue by IamDwight** [sogehige/sogeBot#3109] opened 2019-12-16 18:56 UTC
### Expected behavior 
Everything should be displayed in English.

### Actual behavior 
I have settings enabled to display everything purely in English, which for the most part is correct.  However, there are some aspects that are still very much displayed in an entirely different language.

Seen in these screenshots:
[https://scs.twilightgamez.net/aoprX.png](https://scs.twilightgamez.net/aoprX.png) - Manage > Viewers
[https://scs.twilightgamez.net/IFRQZ.png](https://scs.twilightgamez.net/IFRQZ.png) - Stats > API
This is also seen in Command Output, or really anything to do with displaying dates and times.

Just wanted to point these things out.

### Steps to reproduce 
Select English, play around with the dashboard in it's entirety and notice certain inconsistencies.  
This is apparent mostly with displayed Dates and Times.

### Additional informations 
Log file:
[https://pastebin.com/UPjJESMY](https://pastebin.com/UPjJESMY)
There is no exception.log file on the server. 

The server is hosted in Canada, running CentOS 7. 
Server's system language is set to English, with timezone: America/Toronto

**Comment by sogehige** [comment] 2019-12-18 11:14
Thanks for issue, looks like `moment` have wrongly set language to ru. Interesting, will take a look.

**Comment by sogehige** [comment] 2019-12-18 11:57
Can I see what you have set in your general settings? So far I am not able to reproduce this issue. Can you try to set cs language at #/settings/core/general and check if russian is gone?

**Comment by sogehige** [comment] 2019-12-18 11:58
Also would be nice to have `!_debug` output

**Comment by JesseFST** [comment] 2019-12-18 21:11
Hi.

In #/settings/core/general language it set to "en".
[Screenshot](https://scs.twilightgamez.net/yLR61.png)

Setting the language to "cs" and then back does fix the issue, yes.

Running the command `!_debug` in chat prints this in the `sogebot.log` file:

`2019-12-18T16:10:21.227 <<< !_debug [iamdwight]
2019-12-18T16:10:22.510 !!! ERROR !!! Possibly Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'push' of undefined
      at General.<anonymous> (/opt/TwitchBot/src/bot/general.ts:89:38)
      at Generator.next (<anonymous>)
      at fulfilled (/opt/TwitchBot/dest/general.js:14:58)
} reason: TypeError: Cannot read property 'push' of undefined
`

**Comment by sogehige** [comment] 2019-12-19 00:48
Good you managed to fix that issue. Although !_debug is broken, will fix it and close this issue after.

**Closed** 2019-12-24 15:57 UTC
