### ISSUE TITLE
Doubled bot

### ISSUE THREAD

**Issue by Banonevar** [sogehige/sogeBot#1407] opened 2018-09-30 22:09 UTC
### Actual behavior
![img](https://i.imgur.com/tfe927c.png)
And he answer for commands 2 time
1) some1 use !command
2) bot send 2 responses
### Steps to reproduce
Idk
### Additional informations

Master https://github.com/sogehige/sogeBot/commit/9f4c3ceb81f02c32befe026f8005db9d427cca69, mongodb

**Comment by Banonevar** [comment] 2018-09-30 22:09
Seems like here is doubled chat connection, because follow event not doubled

**Comment by sogehige** [comment] 2018-10-01 08:41
Possibly duplicate of #1401

**Closed by sogehige** 2018-10-01 08:41 UTC

**Comment by Banonevar** [comment] 2018-10-01 08:43
Ok
