### ISSUE TITLE
Wrong uptime

### ISSUE THREAD

**Issue by ghost** [sogehige/sogeBot#1208] opened 2018-08-17 13:58 UTC
### Actual behavior
Bot says stream uptime 21h
but uptime of channel is 0h 25m 9s
### Additional informations

Mongodb, master

**Comment by sogehelper** [comment] 2018-08-17 14:05
2018-08-17T17:03:56.407 DEBUG: ======= COPY DEBUG MESSAGE FROM HERE =======
2018-08-17T17:03:56.409 DEBUG: GENERAL | OS: npm/6.1.0 node/v10.3.0 linux x64 | DB: mongodb | Bot version: 8.0.0-SNAPSHOT | Bot uptime: 1545.708 | Bot lang: ru | Bot mute: false
2018-08-17T17:03:56.409 DEBUG: SYSTEMS | Timer, alias, commercial, cooldown, customCommands, highlights, keywords, moderation, queue, quotes, raffles, songs, timers
2018-08-17T17:03:56.410 DEBUG: GAMES   |
2018-08-17T17:03:56.411 DEBUG: WIDGETS | chat, customvariables, commercial, eventlist, cmdboard, raffles
2018-08-17T17:03:56.411 DEBUG: OAUTH   | BOT true | BROADCASTER true
2018-08-17T17:03:56.412 DEBUG: ======= END OF DEBUG MESSAGE =======

Not sure why i got this issue, i not check uptime before i did restart of bot, but i do restart, and noticed that stream uptime is wrong.

**Comment by sogehige** [comment] 2018-10-02 11:37
Closing, cannot reproduce

**Closed by sogehige** 2018-10-02 11:37 UTC
Labels: cannot reproduce
