### ISSUE TITLE
[9.4.1] UI Previous Page sometimes mixed with actual Page

### ISSUE THREAD

**Issue by tarumes** [sogehige/sogeBot#2409] opened 2019-07-08 20:44 UTC
### Actual behavior
![Unbenannt 1](https://user-images.githubusercontent.com/4124273/60841351-e2fd5200-a1d1-11e9-8230-0392b223bb2d.png)

**Comment by sogehige** [comment] 2019-07-16 13:26
Caused by two routing systems. This will be gradually fixed when moving to new router.

**Closed by sogehige** 2019-07-16 13:26 UTC
Labels: wontfix
