### ISSUE TITLE
(list.alias) must send all alias in chat

### ISSUE THREAD

**Issue by Satont** [sogehige/SogeBot#259] opened 2017-05-11 14:31 UTC
(list.alias) must send all alias in chat, if many aliases, then bot send only 1 message, when its cannot contain all aliases.

**Comment by sogehige** [comment] 2017-05-12 09:22
Cannot reproduce, can you be more specific with steps?

**Comment by Satont** [comment] 2017-05-12 09:26
For example i have 50 aliases, but bot send ~15 in chat
He must send all like this:
Me: !aliases list
Bot: part1
Bot: part2
Bot: part3

**Comment by sogehige** [comment] 2017-05-12 09:38
Aliases was set to private -> closing

**Closed** 2017-05-12 09:38 UTC
Labels: bug, need investigate
